apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    app: fitnessapp
    env: prod
spec:
  template:

    metadata:
     name: mysql
     labels:
        app: fitnessapp
        type: database
    spec:      
      containers:
      - name: mysql
        image: mysql
      - name: tomcat
        image: tomcat    
  replicas: 3  


